name: wh-jcj-update-m3u

on:
  schedule:
    # 每天 UTC 时间 00:00 运行 (即北京时间上午 8:00)
    # 您可以根据需要调整 cron 表达式
    # 更多 cron 表达式信息: https://crontab.guru/
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许手动触发此工作流

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # 确保拉取所有历史记录，以便 git-auto-commit-action 正常工作
        with:
          fetch-depth: 0

      - name: Download and rename wh-tv.m3u
        run: |
          # 使用 curl 下载文件并直接重命名
          curl -o wh-tv.m3u "https://op-wuhan.68642820.xyz/iptv.m3u"
          # 检查下载是否成功，如果文件大小为0，则删除
          if [ ! -s wh-tv.m3u ]; then
            echo "Warning: wh-tv.m3u downloaded file is empty or failed. Deleting it."
            rm -f wh-tv.m3u
          fi


      - name: Download and rename jcj-tv.m3u
        run: |
          # 使用 curl 下载文件并直接重命名
          curl -o jcj-tv.m3u "https://op.sil6864.top:66/iptv.m3u"
          # 检查下载是否成功，如果文件大小为0，则删除
          if [ ! -s jcj-tv.m3u ]; then
            echo "Warning: jcj-tv.m3u downloaded file is empty or failed. Deleting it."
            rm -f jcj-tv.m3u
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # 提交消息
          commit_message: "chore: Update IPTV m3u files"
          # 提交到哪个分支，通常是 main 或 master
          branch: main
          # 如果文件没有变化，则不创建新的提交
          commit_options: '--no-verify --allow-empty'
          # 确保即使没有文件变化也允许空提交，但通常我们只在有变化时提交
          # 如果您希望只有在文件内容实际改变时才提交，可以移除 commit_options
          # 默认情况下，git-auto-commit-action 只有在有实际文件更改时才会提交
